config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resources :recipes, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :cuisines, only: [:show, :new, :create]
  resources :recipe_types, only: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  validates :name, presence: {message: 'Você deve informar o nome da cozinha'}
  validates :name, uniqueness: { case_sensitive: false, message: 'Cozinha já cadastrada' }

  has_many :recipes
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  validates :title, presence: true
  # validates_associated :recipe_type_id
  #validates_associated :cuisine
  # validates :cuisine_id, presence: true
  # validates :difficulty, presence: true
  # validates :cook_time, presence: true
  # validates :ingredients, presence: true
  # validates :method presence: true

  belongs_to :cuisine
  belongs_to :recipe_type
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  validates :name, presence: {message: 'Você deve informar o nome do tipo de receita'}
  validates :name, uniqueness: { case_sensitive: false, message: 'Tipo de receita já cadastrada' }
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  def show
    @cuisine = Cuisine.find(params[:id])
  end
  def new
    @cuisine = Cuisine.new
  end

  def create
    @cuisine = Cuisine.new(cuisine_params)
    if @cuisine.save
      redirect_to cuisine_url(@cuisine.id)
    else
      render :new
    end
  end
  private
  def cuisine_params
    params.require(:cuisine).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.all
    @cuisines = Cuisine.all
    @recipe_types = RecipeType.all
  end
end

app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController
  def show
    @recipe_type = RecipeType.find(params[:id])
  end
  def new
    @recipe_type = RecipeType.new
  end
  def create
    @recipe_type = RecipeType.new(recipe_type_params)
    if @recipe_type.save
      redirect_to recipe_type_url(@recipe_type.id)
    else
      render :new
    end
  end
  private
  def recipe_type_params
    params.require(:recipe_type).permit(:name)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    @cuisines = Cuisine.all
    @recipe_types = RecipeType.all
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @cuisines = Cuisine.all
    @recipe_types = RecipeType.all
  end

  def update
    # @recipe.errors.any?
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to recipe_url(@recipe.id)
    else
      @cuisines = Cuisine.all
      @recipe_types = RecipeType.all
      @recipe.errors.messages
      render :edit
    end
  end
  def destroy
    @recipe = Recipe.find(params[:id])
    if @recipe.destroy
      flash[:error] = 'Receita deletada com sucesso'
      redirect_to root_path
    end
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to recipe_url(@recipe.id)
    else
      flash[:error] = 'Você deve informar todos os dados da receita'
      @cuisines = Cuisine.all
      @recipe_types = RecipeType.all
      render :new
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title,
                                    :recipe_type_id,
                                    :cuisine_id,
                                    :difficulty,
                                    :cook_time,
                                    :ingredients,
                                    :method,
                                    :favorite)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cuisines/new.html.erb
<% if @cuisine.errors.any? %>
  <ul>
    <% @cuisine.errors.full_messages.each do |msg| %>
      <li class="error"><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@cuisine) do |f| %>
  <%= f.label :name, 'Nome'  %>
  <%= f.text_field :name %>
  <br>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/cuisines/show.html.erb
<h1><%= @cuisine.name %></h1>
<% if @cuisine.recipes.empty? %>
  <p>Nenhuma receita encontrada para este tipo de cozinha</p>
<% end %>

<% @cuisine.recipes.each do |recipe| %>
  <h1><%= recipe.title  %></h1>
  <ul>
    <li><%= recipe.recipe_type.name %></li>
    <li><%= recipe.cuisine.name %></li>
    <li><%= recipe.difficulty %></li>
    <li><%= recipe.cook_time %> minutos</li>
  </ul>
<% end %>

app/views/home/index.html.erb
<h1>CookBook</h1>
<p><%= flash[:error] %></p>
<%= link_to 'Enviar uma receita', new_recipe_path %>
<p>Bem-vindo ao maior livro de receitas online</p>



<% @recipes.each do |recipe| %>
  <h1><%= link_to recipe.title, recipe  %></h1>
  <ul>
    <li><%= recipe.difficulty  %></li>
    <li><%= recipe.recipe_type.name  %></li>
    <li><%= recipe.cook_time  %> minutos</li>
    <li><%= recipe.cuisine.name  %></li>
    <li><%= link_to 'Editar', edit_recipe_path(recipe) %></li>
    <li><%= link_to 'Deletar', recipe, method: :delete %></li>
  </ul>
<% end %>


<% @cuisines.each do |cuisine| %>
  <h1><%= cuisine.name  %></h1>
  <%= link_to cuisine.name, cuisine  %>
<% end %>

<% @recipe_types.each do |recipe_type| %>
  <h1><%= link_to recipe_type.name, recipe_type  %></h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipe_types/new.html.erb
<% if @recipe_type.errors.any? %>
  <ul>
    <% @recipe_type.errors.full_messages.each do |msg| %>
      <li class="error"><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@recipe_type) do |f| %>
  <%= f.label :name, 'Nome'  %>
  <%= f.text_field :name %>
  <br>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/recipe_types/show.html.erb
<h1><%= @recipe_type.name %></h1>

<% if @recipe_type.recipes.empty? %>
  Nenhuma receita encontrada para este tipo de receitas
<% end %>

<% @recipe_type.recipes.each do |recipe| %>
  <h1><%= recipe.title  %></h1>
  <ul>
    <li><%= recipe.difficulty  %></li>
    <li><%= link_to recipe.recipe_type.name, recipe.recipe_type  %></li>
    <li><%= recipe.cook_time  %> minutos</li>
    <li><%= recipe.cuisine.name  %></li>
  </ul>
<% end %>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <%= f.label :title, 'Título'  %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :recipe_type_id, 'Tipo da Receita'  %>
  <%= f.collection_select(:recipe_type_id, @recipe_types,
                          :id, :name,
                          { include_blank: true },
                          { class: 'browser-default' }) %>
  <br>
  <%= f.label :cuisine_id, 'Cozinha'  %>
  <%= f.collection_select(:cuisine_id, @cuisines, :id, :name, { class: 'browser-default' }) %>
  <br>
  <%= f.label :difficulty, 'Dificuldade'  %>
  <%= f.text_field :difficulty %>
  <br>
  <%= f.label :cook_time, 'Tempo de Preparo'  %>
  <%= f.text_field :cook_time %>
  <br>
  <%= f.label :ingredients, 'Ingredientes'  %>
  <%= f.text_area :ingredients %>
  <br>
  <%= f.label :method, 'Como Preparar'  %>
  <%= f.text_area :method %>

  <%= f.label :favorite, 'Favorito' %>
  <%= f.check_box(:favorite, {checked:true},  {class: 'browser-default' })  %>
  <br>
  <%= f.submit texto_botao %>
<% end %>

app/views/recipes/edit.html.erb
<% if @recipe.errors.any? %>
  <div class="error">Não pode haver campos em branco</div>
<% end %>
<%= render partial: "form", locals: {texto_botao: 'Salvar'} %>

app/views/recipes/new.html.erb
<%= flash[:error] %>
<%= render partial: "form", locals: {texto_botao: 'Enviar'} %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>
<h3>Detalhes</h3>

<% if @recipe.favorite? %>
  <%= image_tag "star.png" %>
<% end %>

<p>
  Tipo da Receita: <%= link_to @recipe.recipe_type.name, @recipe %>
  Culinária: <%= link_to @recipe.cuisine.name, @recipe  %>
  Dificuldade: <%= @recipe.difficulty %>
  Tempo: <%= @recipe.cook_time %> minutos
</p>

<h3>Ingredientes</h3>
<p><%= @recipe.ingredients %></p>


<h3>Como Preparar</h3>
<p><%= @recipe.method %></p>

<%= link_to 'Voltar',root_path %>